/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_mit_wi_haploview_HaploData */

#ifndef _Included_edu_mit_wi_haploview_HaploData
#define _Included_edu_mit_wi_haploview_HaploData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_wi_haploview_HaploData
 * Method:    callComputeDPrime
 * Signature: (IIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_mit_wi_haploview_HaploData_callComputeDPrime
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     edu_mit_wi_haploview_HaploData
 * Method:    runEM
 * Signature: (II[Ljava/lang/String;I[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_mit_wi_haploview_HaploData_runEM
  (JNIEnv *, jobject, jint, jint, jobjectArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
